# Generated by Django 4.2.2 on 2023-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('cod_chat', models.AutoField(primary_key=True, serialize=False)),
                ('nume_chat', models.CharField(max_length=50)),
                ('continut', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentariu',
            fields=[
                ('cod_comentariu', models.AutoField(primary_key=True, serialize=False)),
                ('continut', models.TextField()),
                ('data_comentariului', models.DateField()),
                ('cod_utilizator', models.IntegerField()),
                ('cod_postare', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('cod_departament', models.AutoField(primary_key=True, serialize=False)),
                ('nume_departament', models.CharField(max_length=50)),
                ('cod_echipa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Echipe',
            fields=[
                ('cod_echipa', models.AutoField(primary_key=True, serialize=False)),
                ('nume_echipa', models.CharField(max_length=50)),
                ('cod_departament', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('cod_forum', models.AutoField(primary_key=True, serialize=False)),
                ('nume_forum', models.CharField(max_length=50)),
                ('descriere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('cod_mesaj', models.AutoField(primary_key=True, serialize=False)),
                ('mesaj', models.CharField(max_length=100)),
                ('data_mesaj', models.DateTimeField()),
                ('cod_utilizator', models.IntegerField()),
                ('cod_chat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Postare',
            fields=[
                ('cod_postare', models.AutoField(primary_key=True, serialize=False)),
                ('titlu', models.CharField(max_length=100)),
                ('continut', models.TextField()),
                ('data_postarii', models.DateField()),
                ('cod_utilizator', models.IntegerField()),
                ('cod_forum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proiect',
            fields=[
                ('cod_proiect', models.AutoField(primary_key=True, serialize=False)),
                ('nume_proiect', models.CharField(max_length=20)),
                ('descriere', models.CharField(max_length=50)),
                ('data_inceput', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('cod_departament', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sedinta',
            fields=[
                ('cod_sedinta', models.AutoField(primary_key=True, serialize=False)),
                ('nume_sedinta', models.CharField(max_length=20)),
                ('descriere', models.CharField(max_length=50)),
                ('data_sedinta', models.DateField()),
                ('ora_inceput', models.TimeField()),
                ('ora_sfarsit', models.TimeField()),
                ('cod_departament', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('cod_task', models.AutoField(primary_key=True, serialize=False)),
                ('nume_task', models.CharField(max_length=20)),
                ('descriere', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('status', models.CharField(max_length=15)),
                ('cod_departament', models.IntegerField()),
                ('cod_echipa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cod_utilizator', models.TextField(max_length=50, unique=True)),
                ('nume', models.TextField(blank=True, max_length=50)),
                ('prenume', models.TextField(blank=True, max_length=50)),
                ('cod_departament', models.IntegerField(blank=True)),
                ('cod_echipa', models.IntegerField(blank=True)),
                ('parola', models.TextField(blank=True, max_length=50)),
                ('adresa_email', models.EmailField(max_length=254, unique=True, verbose_name='adresa email')),
                ('nr_telefon', models.CharField(max_length=15)),
                ('locatie_birou', models.CharField(blank=True, max_length=50)),
                ('atributii', models.CharField(blank=True, max_length=100)),
                ('notificari', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
