# Generated by Django 4.2.2 on 2023-06-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectivityApp', '0003_alter_utilizator_cod_utilizator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizator',
            name='cod_departament',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_echipa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
