# Generated by Django 4.2.2 on 2023-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectivityApp', '0004_alter_utilizator_cod_departament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cod_utilizator',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='cod_utilizator',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comentariu',
            name='cod_utilizator',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='departament',
            name='cod_echipa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='echipe',
            name='cod_departament',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='cod_utilizator',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postare',
            name='cod_utilizator',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proiect',
            name='cod_departament',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sedinta',
            name='cod_departament',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='cod_departament',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='cod_echipa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
