# Generated by Django 4.2.2 on 2023-06-22 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectivityApp', '0005_chat_cod_utilizator_forum_cod_utilizator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='cod_echipa',
        ),
        migrations.AddField(
            model_name='chat',
            name='membrii',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='cod_utilizator',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='nume_chat',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comentariu',
            name='cod_postare',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.postare'),
        ),
        migrations.AlterField(
            model_name='comentariu',
            name='cod_utilizator',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='echipe',
            name='cod_departament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.departament'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='cod_utilizator',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='cod_chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.chat'),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='cod_utilizator',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postare',
            name='cod_forum',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.forum'),
        ),
        migrations.AlterField(
            model_name='postare',
            name='cod_utilizator',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proiect',
            name='cod_departament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.departament'),
        ),
        migrations.AlterField(
            model_name='sedinta',
            name='cod_departament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.departament'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cod_departament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.departament'),
        ),
        migrations.AlterField(
            model_name='task',
            name='cod_echipa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.echipe'),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_departament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.departament'),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_echipa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProjectivityApp.echipe'),
        ),
    ]
