# Generated by Django 4.2.2 on 2023-06-22 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectivityApp', '0006_remove_departament_cod_echipa_chat_membrii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='cod_utilizator',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentariu',
            name='cod_utilizator',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='cod_utilizator',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='cod_utilizator',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postare',
            name='cod_utilizator',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='cod_utilizator',
            field=models.TextField(default='', max_length=50, unique=True),
        ),
    ]
